use HOTEL_SYSTEM;

CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `AGE` INT(10) UNSIGNED,
  `ADRESS` VARCHAR(100) NOT NULL,
  `NATIONALITY` VARCHAR(100),
  `LOGIN` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `ROOM` (
  `ROOM_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NB_BEDS` INT(10) UNSIGNED NOT NULL,
  `PRICE` FLOAT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ROOM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE BOOKING (
  BOOKING_ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NB_ROOMS` INT(10) UNSIGNED NOT NULL,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NOT NULL,
  `CUSTOMER_FK` INT(10) UNSIGNED NOT NULL,
  `ROOMS_FK` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`BOOKING_ID`),
  CONSTRAINT `FK_BOOKING_CUSTOMER`
	FOREIGN KEY (`CUSTOMER_FK`) 
	REFERENCES `CUSTOMER`(`CUSTOMER_ID`)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
  CONSTRAINT `FK_BOOKING_ROOM`
	FOREIGN KEY (`ROOMS_FK`) 
	REFERENCES `ROOM`(`ROOM_ID`)
	ON DELETE CASCADE 
	ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, AGE, ADRESS, NATIONALITY, LOGIN, PASSWORD) VALUES('Naby Daouda', 'Diakite', 23, 'TEST', 'Guinéenne', 'nddiakite', 'admin'); 
INSERT INTO ROOM (NB_BEDS, PRICE) VALUES(2, 2222);
INSERT INTO BOOKING (NB_ROOMS, START_DATE, START_DATE,CUSTOMER_FK, ROOMS_FK) VALUES(2, '2013-01-01 22:22:22', '2013-02-02 22:22:22', 2, 2);

